name: Bluetooth JDY-33 Relay Bridge
version: "1.1.2"
slug: bluetooth-jdy33-relay-bridge
description: MQTT-мост для JDY-33 по BLE (GATT) с автодобавлением свитча в Home Assistant
url: https://github.com/alexanderznamensky/Bluetooth-JDY-33-Relay-Bridge
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
host_network: true
host_dbus: true
bluetooth: true
udev: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - DAC_READ_SEARCH

schema:
  MQTT_HOST: str?
  MQTT_PORT: int?
  MQTT_USER: str?
  MQTT_PASS: str?
  MQTT_PREFIX: str?
  RELAY_NAME: str?
  RELAY_ID: str?
  BLE_ADDR: str?
  BLE_NAME: str?
  BLE_WRITE_CHAR: str?
  CMD_ON_HEX: str?
  CMD_OFF_HEX: str?

options:
  MQTT_HOST: "core-mosquitto"
  MQTT_PORT: 1883
  MQTT_USER: "mqtt"
  MQTT_PASS: "mqtt"
  MQTT_PREFIX: "bluetoothrelay"
  RELAY_NAME: "Bluetooth JDY-33 Relay"
  RELAY_ID: "jdy33_relay"
  BLE_ADDR: "01:B6:EC:11:EF:26"
  BLE_NAME: "JDY"
  BLE_WRITE_CHAR: "0000ffe1-0000-1000-8000-00805f9b34fb"
  CMD_ON_HEX: "A00101A2"
  CMD_OFF_HEX: "A00100A1"


